namespace TSI.Api.Models;

/// <summary>
/// Request body for POST /api/suppliers/{supplierKey}/purchase-orders — create
/// an Inventory supplier PO as a draft. DateOfPO defaults to today when null.
/// PO number is generated by IPONumberService (POType.Inventory) inside the
/// create transaction. The create-time GP guardrail is bGenerated = 0 (GP only
/// consumes generated POs, never drafts).
/// </summary>
public record CreateInventoryPurchaseOrderRequest(
    int ServiceLocationKey,
    int SupplierPOTypeKey,
    DateTime? DateOfPO,
    IReadOnlyList<CreateInventoryPurchaseOrderLine> Lines
);

/// <summary>
/// One row that will become a tblSupplierPOTran. dblItemCost is computed
/// server-side as UnitCost * OrderQuantity; clients send only the inputs.
/// </summary>
public record CreateInventoryPurchaseOrderLine(
    int SupplierSizesKey,
    int OrderQuantity,
    decimal UnitCost
);

/// <summary>
/// Response from a successful create. POTotal is the sum of line dblItemCost
/// values written back to the header in the same transaction.
/// </summary>
public record CreateInventoryPurchaseOrderResponse(
    int SupplierPOKey,
    string SupplierPONumber,
    decimal POTotal
);

/// <summary>
/// Request body for POST /api/acquisitions/purchase-orders — create an
/// Acquisition supplier PO as a draft. DateOfPO defaults to today when null.
/// PO number is generated by IPONumberService (POType.Acquisition) inside the
/// create transaction. The create-time GP guardrail is bGenerated = 0 (GP only
/// consumes generated POs, never drafts); bHoldGPIntegration is also written
/// explicitly as 0 so the row's initial state never depends on ambient column
/// defaults. Unlike the Inventory header, the acquisition header has NO
/// lServiceLocationKey column — ServiceLocationKey here drives the PO# prefix
/// only and is not persisted on the row.
/// </summary>
public record CreateAcquisitionPurchaseOrderRequest(
    int ServiceLocationKey,
    int SupplierKey,
    DateTime? DateOfPO,
    int? PaymentMethodKey,
    IReadOnlyList<CreateAcquisitionPurchaseOrderLine> Lines
);

/// <summary>
/// One row that will become a tblAcquisitionSupplierPOTran. SerialNumber and
/// dtDateReceived/mComment are optional; lScopeTypeKey and nScopeCost are the
/// NOT NULL columns the line table requires.
/// </summary>
public record CreateAcquisitionPurchaseOrderLine(
    int ScopeTypeKey,
    string? SerialNumber,
    decimal ScopeCost
);

/// <summary>
/// Response from a successful create. POTotal is the sum of line ScopeCost
/// values written back to the header in the same transaction.
/// </summary>
public record CreateAcquisitionPurchaseOrderResponse(
    int AcquisitionSupplierPOKey,
    string SupplierPONumber,
    decimal POTotal
);

/// <summary>
/// An open purchase-order line awaiting receipt (ordered &gt; received, PO not
/// cancelled). RemainingQuantity = OrderedQuantity − ReceivedQuantity.
/// </summary>
public record PoReceiptLine(
    int SupplierPOTranKey,
    int SupplierPOKey,
    string PONumber,
    string SupplierName,
    string ItemDescription,
    string SizeDescription,
    int InventorySizeKey,
    int OrderedQuantity,
    int ReceivedQuantity,
    int RemainingQuantity,
    double UnitCost,
    int QtyPerUnit,
    string? PODate
);

/// <summary>
/// Request to receive stock against one PO line. LotNumberOverride is optional —
/// when blank, the server allocates the next lot number; when supplied, that
/// value is used verbatim. Bin / storage / expiration are optional per-receipt
/// physical metadata captured on the ledger row.
/// </summary>
public record ReceivePoLineRequest(
    int SupplierPOTranKey,
    int QuantityReceived,
    string? BinNumber,
    string? StorageLocation,
    DateTime? ExpirationDate,
    string? LotNumberOverride
);

/// <summary>
/// Result of a receipt: the lot number written to the ledger row, the PO line's
/// new received-to-date total, and the size's new on-hand level at the location.
/// </summary>
public record ReceivePoLineResponse(
    string LotNumber,
    int ReceivedQuantityTotal,
    int NewLocationLevel
);
